### ISSUE TITLE
problem running on linux mint 18.3

### ISSUE THREAD

**Issue by dhdurgee** [fraunhoferfokus/peer-dial#18]
I encountered this tool today and installed it for possible in my environment.  It appeared to have installed properly via npm install peer-dial, but when I attempted to run the test client I see:

```
dhdurgee@Z560 ~/Downloads $ node node_modules/peer-dial/test/dial-client.js
/perm/home/dhdurgee/Downloads/node_modules/xmlbuilder/lib/index.js:5
  ({assign, isFunction} = require('./Utility'));
   ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/perm/home/dhdurgee/Downloads/node_modules/xml2js/lib/xml2js.js:12:13)
    at Object.<anonymous> (/perm/home/dhdurgee/Downloads/node_modules/xml2js/lib/xml2js.js:513:4)
    at Module._compile (module.js:410:26)
```

In case this might be version related:

```
dhdurgee@Z560 ~/Downloads $ node -v
v4.2.6
```

This is my first attempt in this area, so it is quite possible this is my problem.  I am hoping to use this tool to create a script to start youtube on a Blu-ray player and have it play an internet stream.  I would need to be able to stop the stream at any time and start another internet stream when desired.

**Comment by dhdurgee** [comment]
I updated the nodejs and now get:

```
dhdurgee@Z560 ~/Downloads $ node node_modules/peer-dial/test/dial-client.js
DIAL client is ready
DIAL device found
Request DIAL device description from http://192.168.80.196:50201/dial.xml
Got DIAL device description:  DialDevice {
  descriptionUrl: 'http://192.168.80.196:50201/dial.xml',
  applicationUrl: 'http://192.168.80.196:50202/apps',
  deviceType: 'urn:schemas-upnp-org:device:Basic:1',
  friendlyName: 'BDP-S1700',
  manufacturer: 'Sony Corporation',
  modelName: 'Blu-ray Disc Player',
  UDN: 'uuid:00000004-0000-1010-8000-cc988b6fe1dc',
  icons: [] }
Request YouTube DIAL App from http://192.168.80.196:50202/apps
Got YouTube App Info from http://192.168.80.196:50202/apps/YouTube
YouTube Launched Successfully 

```

So this was due to an outdated node release.  I am now running v8.17.0 with this.  Now I need documentation on using YouTube via DIAL.

**Comment by louaybassbouss** [comment]
@dhdurgee good to hear that is now working. Regarding "documentation on using YouTube via DIAL": this is not part of the DIAL Spec. DIAL allows to send data in the body of the Launch HTTP Post Request. It is up to the App to define the structure of the data. I will close this issue. If you encounter other problems please open new issues.
