### ISSUE TITLE
Missing "SERVER" field in "200 OK" responses to search requests.

### ISSUE THREAD

**Issue by matt-hammond-bbc** [fraunhoferfokus/peer-dial#3]
The UPnP Device Architecture v1.x requires that messages sent by the server include a "SERVER" field. This is missing from the "200 OK" UDP responses but is present in other message.

The field needs to be a string containing space-separated "product tokens" of the form "NAME/VERSION". The first three tokens need to be: about the OS, UPnP stack and product. e.g. “SERVER: unix/5.1 UPnP/1.1 MyProduct/1.0”

See http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf page 23
 @matt-hammond-bbc

(Previously raised as https://github.com/fraunhoferfokus/peer-ssdp/issues/5 )

**Comment by aldafu** [comment]
fixed by #4
