### ISSUE TITLE
Need to support CORS

### ISSUE THREAD

**Issue by matt-hammond-bbc** [fraunhoferfokus/peer-dial#5]
https://github.com/fraunhoferfokus/node-hbbtv/issues/4 requires support for adding CORS headers to HTTP responses by the DIAL server.

**Comment by aldafu** [comment]
The DIAL spec has the following bit about CORS:

```
6.5 CORS Requirements and CORS Access Control Policy

In addition to the CORS check made on additionalDataUrl, all Application Resource URLs

are subject to the following policy:

Whenever an HTTP request is made against an Application Resource, the DIAL server should run

the following checks:

1. If the ORIGIN header is absent in the request, the CORS check is not applicable and the

request is allowed.

2. If the ORIGIN header is present in the request:

a. ORIGIN headers that don't start with 'http', 'https', or 'file' are automatically

accepted.

b. The ORIGINheader must match one of the authorized domains provided by the

DIAL application.
```

Therefor I think an express middleware that always runs on requests against /apps/* and follows the spec as quoted above would be the best way to do it, correct?

I also noted you've included the OPTIONS method, which is not used by DIAL. Did you include it because e.g. Chrome-based browsers like to fire an OPTIONS request before continuing with GET/POST? I wonder if it is needed.

**Comment by matt-hammond-bbc** [comment]
Thanks for checking this. OPTIONS is probably not needed in the list of allowed headers.

You are proposing that cross origin rules are enforced on a per-DIAL-application basis?

**Comment by matt-hammond-bbc** [comment]
I have done some more checking ... The HbbTV 2.0 specification requires that preflight CORS requests (OPTIONS requests) are supported. See clause 14.8 "Cross-Origin support":

> If the request uses the OPTIONS method, the HbbTV terminal shall process the request as a preflight request in accordance with clause 6.2 of the W3C Cross-Origin Resource Sharing recommendation ...

**Comment by aldafu** [comment]
> 2. CORS headers should not be included unless an ORIGIN header is included in the initial request (My PR always includes the CORS headers)

Yes, that would match the spec.

> 1. cross origin rules are enforced on a per-DIAL-application basis? (My PR makes it apply a single rule to all applications)

Here I meant no per app basis, but apply it only to those requests against the /apps/ path. We have a single route on the non standard app path /ssdp/ which already uses CORS headers. That shoudn't interfere with the CORS headers for the /apps/ path. See: https://github.com/fraunhoferfokus/peer-dial/blob/d9de24dd182edd5b0e03a40c68872d9c041cf79a/lib/peer-dial.js#L157

For the OPTIONS requests, I guess we can keep it then. Alternative would be to make the methods also configurable through the options as well, but maybe that's a bit too much.

**Comment by matt-hammond-bbc** [comment]
I've submitted a pull request with a new implementation that should address the issues you raised.

**Comment by aldafu** [comment]
Thanks Matt. I took your changes and added some of my own over at #8. Mainly I implemented more of the CORS policy as described in the DIAL specifcation. Could you look at the changes and verify that your use case still works with these changes?

**Comment by matt-hammond-bbc** [comment]
Many thanks - your additional changes look sensible to me. They don't seem to cause any problems for my use case.
